export { default as LoginPage } from "./LoginPage";
export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as OrderListContainer } from "./orderList/first_page";
export { default as OrderList } from "./orderList/OrderList";
export { default as OrderRow } from "./orderList/OrderRow";
export { default as OrderDetail } from "./orderList/second_page";
export { default as ApplyLossPage } from "./test/ApplyLoss";
export { default as TestPage } from "./test/test";