# Generated by Django 3.2.12 on 2022-04-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('mailId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('confirmFlag', models.CharField(max_length=1)),
                ('lastLogTime', models.DateTimeField()),
                ('editDatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('foundOrLoss', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=1)),
                ('accountId', models.CharField(max_length=200)),
                ('lossDatetime', models.DateTimeField()),
                ('itemPlace', models.CharField(max_length=200)),
                ('preservePlace', models.CharField(max_length=200)),
                ('itemType', models.CharField(max_length=200)),
                ('itemDesc', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='')),
                ('closeDatetime', models.DateTimeField()),
                ('itemOwnerId', models.CharField(max_length=200)),
                ('editDatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemTypeLevel1',
            fields=[
                ('level1Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('editDatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='ntulost.order')),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account1', models.CharField(max_length=200)),
                ('account2', models.CharField(max_length=200)),
                ('itemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntulost.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTypeLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level2Id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('editDatetime', models.DateTimeField()),
                ('level1Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level2Items', to='ntulost.itemtypelevel1')),
            ],
            options={
                'unique_together': {('level1Id', 'level2Id')},
            },
        ),
        migrations.CreateModel(
            name='ChatContext',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('send_account', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=200)),
                ('sendDatetime', models.DateTimeField()),
                ('chatroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contexts', to='ntulost.chatroom')),
            ],
            options={
                'unique_together': {('chatroom', 'seq')},
            },
        ),
    ]
