# Generated by Django 4.0.3 on 2022-04-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='closeDatetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemOwnerId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='preservePlace',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
