# Generated by Django 4.0.3 on 2022-04-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0002_alter_item_closedatetime_alter_item_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='editDatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
