# Generated by Django 4.0.3 on 2022-04-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0003_alter_item_editdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
