# Generated by Django 4.0.3 on 2022-04-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0004_alter_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcontext',
            old_name='send_account',
            new_name='sendAccount',
        ),
        migrations.AlterField(
            model_name='account',
            name='editDatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatcontext',
            name='sendDatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemtypelevel1',
            name='editDatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemtypelevel2',
            name='editDatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
