# Generated by Django 4.0.3 on 2022-04-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0006_alter_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(null=True, upload_to='images')),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemtypelevel2',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='confirmFlag',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastLogTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='chatcontext',
            name='context',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chatcontext',
            name='sendAccount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='accountId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='closeDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDesc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemOwnerId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemPlace',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lossDatetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('finding', 'finding'), ('done', 'done'), ('contact', 'contact')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemtypelevel2',
            name='level2Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
