# Generated by Django 4.0.3 on 2022-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0007_preserveplace_remove_itemtypelevel2_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
        migrations.RemoveField(
            model_name='preserveplace',
            name='img',
        ),
        migrations.AddField(
            model_name='account',
            name='photoPath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='imgPath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='preserveplace',
            name='imgPath',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
