# Generated by Django 4.0.3 on 2022-04-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0008_alter_account_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phoneNumber',
        ),
    ]
