# Generated by Django 4.0.3 on 2022-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0008_itemplace_remove_account_photo_remove_item_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='photoPath',
        ),
        migrations.RemoveField(
            model_name='item',
            name='imgPath',
        ),
        migrations.RemoveField(
            model_name='preserveplace',
            name='imgPath',
        ),
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='preserveplace',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='chatcontext',
            name='sendDatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
