# Generated by Django 4.0.3 on 2022-04-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0009_remove_account_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
