# Generated by Django 4.0.3 on 2022-04-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0009_remove_account_photopath_remove_item_imgpath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPair',
            fields=[
                ('lossItemId', models.IntegerField(primary_key=True, serialize=False)),
                ('foundItemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foundId', to='ntulost.item')),
            ],
            options={
                'unique_together': {('foundItemId', 'lossItemId')},
            },
        ),
        migrations.DeleteModel(
            name='ItemPlace',
        ),
        migrations.AlterField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatcontext',
            name='sendDatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
