# Generated by Django 4.0.3 on 2022-04-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0010_itempair_delete_itemplace_alter_account_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
            ],
        ),
    ]
