# Generated by Django 4.0.3 on 2022-04-21 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0012_alter_chatcontext_senddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempair',
            name='foundItemId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foundId', to='ntulost.item'),
        ),
    ]
