# Generated by Django 4.0.3 on 2022-04-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0013_alter_itempair_founditemid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPair',
        ),
    ]
