# Generated by Django 4.0.3 on 2022-04-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0015_itempair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatContext',
        ),
    ]
