# Generated by Django 4.0.3 on 2022-04-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0018_alter_itempair_founditemid_alter_itempair_lossitemid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('sendAccount', models.CharField(max_length=200, null=True)),
                ('context', models.CharField(max_length=200, null=True)),
                ('sendDatetime', models.DateTimeField(null=True)),
                ('chatroomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='ntulost.chatroom')),
            ],
            options={
                'unique_together': {('chatroomId', 'seq')},
            },
        ),
    ]
