# Generated by Django 4.0.3 on 2022-04-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0019_chatcontext'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatcontext',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chatcontext',
            name='seq',
        ),
    ]
