# Generated by Django 4.0.3 on 2022-04-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0020_alter_chatcontext_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
