# Generated by Django 4.0.3 on 2022-04-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntulost', '0010_account_phonenumber'),
        ('ntulost', '0021_remove_orderitem_order_delete_order_delete_orderitem'),
    ]

    operations = [
    ]
